Automatic connection reconnecting
surrealdb/surrealdb.js pull request #385
Opened 2024-11-25 16:28 UTC by macjuul

Thank you for submitting this pull request! We appreciate you spending the time to work on these changes.

## What is the motivation?

The JavaScript SDK currently does not offer any functionality for automatically recovering from an unexpected disconnect. Additionally, this functionality is desired by many users and will greatly benefit from an internal standardised implementation.

## What does this change do?

Implements a new `reconnect` option passed to `connect()` which takes a boolean or a reconnect options object.

### Reconnect options

- `enabled`: Whether the SDK will attempt to reconnect after disconnecting (default `true`)
- `interval`: The time in milliseconds to wait before reconnecting (default `5000`)
- `attempts`: The maximum amount of connection attempts (default `5`)
- `options`: A callback for customising the connection options (optional)

### Notes

- Pass any negative number to `attempts` in order to continue reconnecting infinitely
- You can use `options` to pass up-to-date authentication details to reconnect attempts
- Executed queries will continue to await until the connection is re-established, or reject after the maximum amount of attempts have been reached
- Closing a connection manually using `close()` will not trigger a reconnect

## What is your testing strategy?

TBD

## Is this related to any issues?

#203

## Have you read the [Contributing Guidelines](https://github.com/surrealdb/surrealdb.js/blob/main/CONTRIBUTING.md)?

- [x] I have read the [Contributing Guidelines](https://github.com/surrealdb/surrealdb.js/blob/main/CONTRIBUTING.md)

2024-11-25 19:15 UTC, ntorrey commented
Does the 'pinger' logic need to be updated? I believe that is what was throwing errors before. If it tried to ping the websocket connection when the connection was down it would make the application crash.

2024-11-26 13:56 UTC, macjuul commented on src/surreal.ts
> +const DEFAULT_RECONNECT_OPTIONS: ReconnectOptions = {
Alright I've added support for exponential backoff, replacing the `interval` property with the following new properties

- `retryDelay` The base delay to wait between each attempt (default 1000)
- `retryDelayMax` The maximum amount of time to wait between attempts (default 60000)
- `retryDelayMultiplier` The amount to multiply each delay by (default 2)
- `retryDelayJitter` A percentage to randomly offset each delay by (default 0.1)

2024-11-26 14:13 UTC, macjuul commented
@ntorrey The pinger should already be cleaning up correctly, however since the pinger exists to keep the socket open, I've made it ignore potential errors since we don't handle these anyways. This might resolve the error itself, however doesn't explain why socket closing isn't handled correctly

2024-11-27 21:49 UTC, LucyEgan commented
@ntorrey i notice this same behaviour with our reconnection logic(which is the same ish implementation as this except outside of the sdk) It will also happens on desktop between pc sleeps/backgrounded browser tabs. And i would assume the same with mobile(outside of pwa) and general backgroundedness of things. Im not sure of a reliable way to test/reproduce it so that it can be properly implemented to handle this as of yet

2024-11-27 21:51 UTC, ntorrey commented
@LucyEgan Thanks! 
So I was able to peek into the console of the mobile app and I get this error:
`ERROR NoActiveSocket: No socket is currently connected to a SurrealDB instance. Please call the .connect() method first!`
But Claude AI came to the rescue. There _is_ an event that fires when the app is brought back from the background. I just need to see the best way to leverage this and if it solves the issue.
```
document.addEventListener('visibilitychange', () => {
  if (document.visibilityState === 'visible') {
    // The page has become visible again (app brought back from background)
    // connect() logic goes here
  }
});
```

2024-11-27 21:58 UTC, LucyEgan commented
@ntorrey yeh thats what i was thinking, but beware that will get triggered each time you view the pwa/tab/window again (good old ai suggesting good enough stuff 🤣)
I would like to see the sdk handle this if possible to not give you a `NoActiveSocket` when it expects to be in a connected/reconnecting state, but hang the queries(in order) until the reconnection/persistence is complete and only fail when its actually not connected.

I would probably do that bit my side if its not in the sdk, but i feel like all these extra cases should be handled otherwise you end up implementing the rest of connection management outside anyway

2024-11-28 00:48 UTC, ntorrey commented
Sorry for spamming this PR, but hopefully this is helpful. Another case that has happened to me is on the server. When my fly.io instance is suspended and restarts I get the same error.

2024-12-19 18:02 UTC, triracle97 commented
What happens if the ping fails to ping the server. I'm encountering a case where the connection status is connected but I can't send anything to the database (ws requests keep hanging). In this case the only solution is to restart the whole web tab and create a new connection. 
I'm on 1.0.0-alpha.9, but I think the new version still has this issue, I'm encountering it using surrealist also

2025-02-18 18:06 UTC, LucyEgan requested changes

2025-02-19 10:14 UTC, kearfy commented on src/util/reconnect.ts
> +	get allowed(): boolean {
Thanks! Added this in 7f65ef1

2025-02-19 10:14 UTC, kearfy commented on src/engines/ws.ts
> +							await this.rpc(
Thanks! Added this in 7f65ef1

2025-02-19 10:25 UTC, LucyEgan commented on src/engines/ws.ts
> +					} catch (e) {
@kearfy thanks for adding my suggestions, I'm not sure if this is needed after your recent merge of other changes/tests, but previously I needed `if(e instanceof EngineDisconnected) continue;` here to allow the newly added `throw` to reattempt rather than hard fail.

2025-04-03 11:59 UTC, merged